export const internalLink = {
  PARTNER: '/partner',
  SHIPPER: '/shipper',
  CUSTOMER: '/customer',
  CUSTOMER_ORDER: '/customer/order',
  SIGN_UP: '/sign-up',
  SIGN_UP_PARTNER: '/sign-up/partner',
  SIGN_UP_SHIPPER: '/sign-up/shipper',
  NEW_DISH: '/partner/menu/add',
  NEW_ORDER: '/partner/order/add',
  LOGIN: '/login',
  PARTNER_UPDATE_DISH: '/partner/menu/update/:id',
  HOME: '/',
  DIVIDER: '/',
  KEY_NAVBAR_INDEX: 2,
  ROLE_INDEX: 1,
};
