export const keyRegisterShipper = {
  USERNAME: 'username',
  FULL_NAME: 'fullName',
  PASSWORD: 'password',
  CONFIRM_PASSWORD: 'confirmPassword',
  EMAIL: 'email',
  PHONE: 'phone',
  ADDRESS: 'address',
  PROVINCE: 'province',
  DISTRICT: 'district',
  NATIONAL_ID: 'nationalId',
  LICENSE_PLATE: 'licensePlate',
  ACTIVE_AREA: 'activeArea',
  BANK_ACCOUNT: 'banking',
};
